fix(dw-126): Add Open Graph (social media infos)
BanklessDAO/bankless-website pull request #115
Opened 2023-02-07 14:18 UTC by c2j

2023-02-07 20:05 UTC, MantisClone requested changes
Hi, @c2j Overall it looks good. 

One small change request: Can you use the BanklessDAO Logo stored here: https://drive.google.com/file/d/1UJ00icQ23avjr_Elq3FlPuDszhDswzfk/view?usp=sharing

2023-02-07 20:07 UTC, MantisClone commented
Note to self: test using https://www.opengraph.xyz/

2023-02-09 15:18 UTC, c2j commented
use the BanklessDAO Logo stored here: https://drive.google.com/file/d/1UJ00icQ23avjr_Elq3FlPuDszhDswzfk/view?usp=sharing
Put the logo as /icons/bankless-log-2.png

2023-02-09 16:39 UTC, MantisClone approved these changes

2023-02-09 16:40 UTC, merged