TlBank
BanklessDAO/bankless-website pull request #190
Opened 2023-07-07 01:02 UTC by LordRanchoatos

TlBank integration

2023-07-10 14:43 UTC, MantisClone requested changes
Please upgrade to Node 16 or above.

Vercel errors:

```
Running build in Washington, D.C., USA (East) – iad1
--
05:20:49.876 | Cloning github.com/BanklessDAO/bankless-website (Branch: main, Commit: cfef785)
05:20:56.801 | Cloning completed: 6.925s
05:20:57.119 | Restored build cache
05:20:57.161 | Running "vercel build"
05:20:57.670 | Vercel CLI 31.0.1
05:20:57.983 | Error: Node.js version 14.x has reached End-of-Life. Deployments created on or after 2023-08-15 will fail to build. Please set Node.js Version to 18.x in your Project Settings to use Node.js 18.
05:20:57.991 | Installing dependencies...
05:20:58.293 | yarn install v1.22.17
05:20:58.388 | [1/4] Resolving packages...
05:20:58.988 | [2/4] Fetching packages...
05:21:33.934 | error svelte-i18n@3.6.0: The engine "node" is incompatible with this module. Expected version ">= 16". Got "14.21.3"
05:21:33.935 | error Found incompatible module.
05:21:33.935 | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
05:21:33.969 | Error: Command "yarn install" exited with 1
```

2023-07-10 15:01 UTC, MantisClone requested changes
There are a significant number of changes here. Can you please add a PR description or link to documentation that describes this code's design and intended operation? Such a description will drastically shorten the time it takes me to review. (It will take me longer if I figure it out myself). I think a discussion of why core design decisions were made would be helpful too.

2023-07-10 15:13 UTC, MantisClone requested changes

2023-07-10 15:13 UTC, MantisClone commented on tlUtils/config.js
> +export const GOERLI_RPC_URL = `https://goerli.infura.io/v3/9344a875cace468ca6c8029147cda56a`
I think we'll need to create repository or vercel secrets for these Project IDs.

2023-07-10 15:13 UTC, MantisClone commented on tlUtils/config.js
> +  projectId: 'e1726502f108ccc7845fc598e1a605f3',
I think we'll need to create a repository or vercel secret for this project ID.

2023-07-10 15:21 UTC, MantisClone commented
CC @Icedcool

2023-07-12 01:57 UTC, Icedcool commented on pages/tlBank.tsx
> +const API = '9176eee3-12fa-431c-93c5-27d1f40d4c91'
A repository works for me?

I would defer to what you think is best.

2023-07-12 02:34 UTC, Icedcool commented
So I just forked https://github.com/LordRanchoatos/bankless-website and built it locally, and it is saying the node version is "17.0.14".

2023-07-12 22:35 UTC, MantisClone commented
> Please upgrade to Node 16 or above.

The node version was a Vercel setting set to version 14! I fixed the Vercel build by upgrading to Node 18. CC @Icedcool @LordRanchoatos 
![image](https://github.com/BanklessDAO/bankless-website/assets/2530913/f54db3f4-1bee-496c-aaf0-40cc8efd0fe6)

2023-07-12 22:36 UTC, MantisClone commented
@Icedcool I quickly clicked through the top-nav bar but couldn't find the TLBank page. At what URL path is it located?

2023-07-13 05:13 UTC, Icedcool commented
@MantisClone Should just be */tlBank.

2023-07-13 14:17 UTC, Icedcool commented
https://bankless-website-git-fork-lordranchoatos-main-banklessdao.vercel.app/tlBank

Looking good!

2023-07-16 04:15 UTC, closed without merging