fix: Fix card error on about-us for safari
BanklessDAO/bankless-website pull request #242
Opened 2023-09-21 20:13 UTC by amochuko

Fixed error on about-us for safari and page display feels natural

2023-09-25 20:26 UTC, MantisClone requested changes
These changes make the images appear distorted on Brave (and I'll assume the same is true on Chrome). Can you make it look good on all browsers(Chrome, Brave, Edge, Firefox, Safari, etc.)?

This PR:
![image](https://github.com/BanklessDAO/bankless-website/assets/2530913/af24590f-ceb9-464b-94db-93e5bea36fae)

Compare to Current Live Site:
![image](https://github.com/BanklessDAO/bankless-website/assets/2530913/14dd0c50-8479-404b-867f-10cad1e2a2df)

2023-10-03 01:18 UTC, MantisClone reviewed
I tested on Brave and Firefox. Both are working :+1: 

@BOBOtoTHEmoon I can't test on Safari. Can you?

Conversely, @amochuko can you post a Safari screenshot?

2023-10-03 05:15 UTC, amochuko commented
<img width="1316" alt="Screenshot 2023-10-03 at 06 11 47" src="https://github.com/BanklessDAO/bankless-website/assets/7204868/dbe25689-9702-44db-997b-6bf1ae202dab">
<img width="1316" alt="Screenshot 2023-10-03 at 06 11 37" src="https://github.com/BanklessDAO/bankless-website/assets/7204868/3a72c230-da20-4492-a9ef-089be85b7b5f">
<img width="1316" alt="Screenshot 2023-10-03 at 06 11 28" src="https://github.com/BanklessDAO/bankless-website/assets/7204868/6ca55279-aff7-4353-bf45-eeec8c351a23">
<img width="1316" alt="Screenshot 2023-10-03 at 06 11 19" src="https://github.com/BanklessDAO/bankless-website/assets/7204868/eddea764-7d06-493e-8d21-ccb652b9c6a3">
<img width="1316" alt="Screenshot 2023-10-03 at 06 11 13" src="https://github.com/BanklessDAO/bankless-website/assets/7204868/ac2b6a96-fd8c-4f85-9dfb-84adcde939a9">
<img width="1316" alt="Screenshot 2023-10-03 at 06 10 40" src="https://github.com/BanklessDAO/bankless-website/assets/7204868/1f40fb03-2e9c-409f-944f-3f91476c38be">
<img width="1316" alt="Screenshot 2023-10-03 at 06 10 22" src="https://github.com/BanklessDAO/bankless-website/assets/7204868/7ce3c2b4-e487-4245-9702-4d4d3f9d3237">
<img width="1316" alt="Screenshot 2023-10-03 at 06 10 12" src="https://github.com/BanklessDAO/bankless-website/assets/7204868/910378f1-a632-47e2-8497-b6828317387e">
<img width="1316" alt="Screenshot 2023-10-03 at 06 09 59" src="https://github.com/BanklessDAO/bankless-website/assets/7204868/09602fed-b034-4e47-ad76-9800f9f635d9">
<img width="1385" alt="Screenshot 2023-10-03 at 06 09 17" src="https://github.com/BanklessDAO/bankless-website/assets/7204868/1a94ba49-95ab-433f-b278-6327edf50095">

2023-10-03 10:58 UTC, MantisClone approved these changes

2023-10-03 18:14 UTC, merged