feat: Work with us via notion CMS
BanklessDAO/bankless-website pull request #260
Opened 2023-10-14 12:00 UTC by didierkrux

PR contains the following:
- semi-dynamic `work with us` page based on our Notion CMS https://bankless.notion.site/6b3a4ffc3bb146a7873e654f1209d979?v=356a2069ddda4563ae96b571e51b913d&pvs=4
- moved the section component to _common + made a couple improvements (simplified props + better image display)
- deleted a bunch of old code (tab UI / carousel)
- when an image is replaced, the previous one gets automatically removed
- updated images for the following projects: Making Bank (removed white border) + Daolationships (removed white border) + Bankless Academy + DaoStewards

2023-10-17 01:43 UTC, MantisClone requested changes
Great work! Just one minor fix.

2023-10-17 01:43 UTC, MantisClone commented on pages/work-with-us/index.tsx
> +          <SectionTitle title={category.title} description={category.title} />
Should be `category.description`
![image](https://github.com/BanklessDAO/bankless-website/assets/2530913/fecc3259-4754-4dc4-8531-12673f84ad5a)


```suggestion
<SectionTitle title={category.title} description={category.description} />
```

2023-10-18 10:49 UTC, didierkrux commented
> Great work! Just one minor fix.

Thanks, good catch 🙂

2023-10-26 21:24 UTC, MantisClone approved these changes

2023-10-26 21:39 UTC, merged