Update guild.tsx
BanklessDAO/bankless-website pull request #73
Opened 2023-01-13 20:35 UTC by BOBOtoTHEmoon

2023-01-13 21:36 UTC, MantisClone requested changes
@BOBOtoTHEmoon Thanks for this PR.  I realized the text we provided you was not grammatically correct so I added some minor changes.

2023-01-13 21:36 UTC, MantisClone commented on components/about-us/sub-pages/guilds/guild.tsx
> +                  content, and as a culture, we reward action and embrace risk.'
```suggestion
                  content. As a culture, we reward action and embrace risk.'
```

2023-01-13 21:36 UTC, MantisClone commented on components/about-us/sub-pages/guilds/guild.tsx
> +                  narrative through visual aid, generate funding through art, always using integrity in our images and
```suggestion
                  narrative through visual aid, and generate funding through art. We use integrity in our images and
```

2023-01-13 21:56 UTC, BOBOtoTHEmoon commented
oh, thank you ser

On Fri, Jan 13, 2023 at 22:36 MantisClone ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> @BOBOtoTHEmoon <https://github.com/BOBOtoTHEmoon> Thanks for this PR. I
> realized the text we provided you was not grammatically correct so I added
> some minor changes.
> ------------------------------
>
> In components/about-us/sub-pages/guilds/guild.tsx
> <https://github.com/BanklessDAO/bankless-website/pull/73#discussion_r1070090389>
> :
>
> > @@ -58,9 +58,9 @@ function Guild() {
>
>            />
>
>            <Section
>
>              title='Design Guild'
>
> -            text='The DAOlationships Guild facilitates and coordinates relationships between external organizations and
>
> -          the guilds within BanklessDAO.
>
> -          This guild helps us best represent our DAO to anyone outside bDAO.'
>
> +            text='Clear communication of the DAO mission through intelligent next-gen design. We establish powerful symbols, build a
>
> +                  narrative through visual aid, generate funding through art, always using integrity in our images and
>
> +                  content, and as a culture, we reward action and embrace risk.'
>
>
> ⬇️ Suggested change
>
> -                  content, and as a culture, we reward action and embrace risk.'
>
> +                  content. As a culture, we reward action and embrace risk.'
>
>
> ------------------------------
>
> In components/about-us/sub-pages/guilds/guild.tsx
> <https://github.com/BanklessDAO/bankless-website/pull/73#discussion_r1070090454>
> :
>
> > @@ -58,9 +58,9 @@ function Guild() {
>
>            />
>
>            <Section
>
>              title='Design Guild'
>
> -            text='The DAOlationships Guild facilitates and coordinates relationships between external organizations and
>
> -          the guilds within BanklessDAO.
>
> -          This guild helps us best represent our DAO to anyone outside bDAO.'
>
> +            text='Clear communication of the DAO mission through intelligent next-gen design. We establish powerful symbols, build a
>
> +                  narrative through visual aid, generate funding through art, always using integrity in our images and
>
>
> ⬇️ Suggested change
>
> -                  narrative through visual aid, generate funding through art, always using integrity in our images and
>
> +                  narrative through visual aid, and generate funding through art. We use integrity in our images and
>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BanklessDAO/bankless-website/pull/73#pullrequestreview-1248560506>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3MP7JJIX7ET2J5EJ5DE373WSHDG5ANCNFSM6AAAAAAT2ZN2HM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-19 00:38 UTC, MantisClone approved these changes

2023-01-19 00:38 UTC, merged